# NLP2 Official WMT Consistency Check
# Goal:
# Try the official WMT25 terminology consistency metric in a separate notebook.
# This notebook does not modify the main experiments.

In [1]:
!pip install -q pandas numpy sacrebleu tqdm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 8.1 MB/s eta 0:00:00

In [2]:
!git clone https://github.com/wmt-conference/wmt25-terminology.git

Cloning into 'wmt25-terminology'...
remote: Enumerating objects: 1097, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 1097 (delta 30), reused 85 (delta 22), pack-reused 1001 (from 1)
Receiving objects: 100% (1097/1097), 66.55 MiB | 21.70 MiB/s, done.
Resolving deltas: 100% (614/614), done.

In [14]:
!find wmt25-terminology/additional_metrics/term-consistency -maxdepth 2 -type f
!ls -lh wmt25-terminology/additional_metrics/term-consistency

wmt25-terminology/additional_metrics/term-consistency/pseudorefs/pseudorefs.zip
wmt25-terminology/additional_metrics/term-consistency/pseudorefs/README.md
wmt25-terminology/additional_metrics/term-consistency/docpreprocessor.py
wmt25-terminology/additional_metrics/term-consistency/openai-api-key.txt
wmt25-terminology/additional_metrics/term-consistency/requirements.txt
wmt25-terminology/additional_metrics/term-consistency/fewshot/en-de-20.txt
wmt25-terminology/additional_metrics/term-consistency/fewshot/en-ru-20.txt
wmt25-terminology/additional_metrics/term-consistency/fewshot/en-zh-20.txt
wmt25-terminology/additional_metrics/term-consistency/fewshot/zh-en-20.txt
wmt25-terminology/additional_metrics/term-consistency/fewshot/en-es-20.txt
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enes.noterm.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-ende.noterm.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enru.proper.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-zhen.noterm.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-ende.proper.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enzh.random.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-zhen.proper.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-ende.random.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enzh.proper.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-zhen.random.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enru.noterm.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enes.random.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enes.proper.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enzh.noterm.json
wmt25-terminology/additional_metrics/term-consistency/stats/stats-enru.random.json
wmt25-terminology/additional_metrics/term-consistency/processed/processed.zip
wmt25-terminology/additional_metrics/term-consistency/processed/README.md
wmt25-terminology/additional_metrics/term-consistency/script_track2.py
wmt25-terminology/additional_metrics/term-consistency/script_track1.py
wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py
wmt25-terminology/additional_metrics/term-consistency/README.md
wmt25-terminology/additional_metrics/term-consistency/track2-sent-alignment.ipynb
total 136K
drwxr-xr-x 3 root root 4.0K May 20 21:28 data
-rw-r--r-- 1 root root  17K May 20 21:28 docpreprocessor.py
drwxr-xr-x 2 root root 4.0K May 20 21:28 fewshot
-rw-r--r-- 1 root root   21 May 20 21:28 openai-api-key.txt
drwxr-xr-x 2 root root 4.0K May 20 21:28 processed
drwxr-xr-x 2 root root 4.0K May 20 21:28 pseudorefs
-rw-r--r-- 1 root root 2.4K May 20 21:28 README.md
-rw-r--r-- 1 root root  18K May 20 21:28 requirements.txt
-rw-r--r-- 1 root root 3.7K May 20 21:28 script_track1.py
-rw-r--r-- 1 root root 3.5K May 20 21:28 script_track2.py
drwxr-xr-x 2 root root 4.0K May 20 21:28 stats
-rw-r--r-- 1 root root  38K May 20 21:28 termbasedmetric.py
-rw-r--r-- 1 root root  19K May 20 21:28 track2-sent-alignment.ipynb

In [16]:
from google.colab import files
uploaded = files.upload()
print(uploaded.keys())

Saving nlp2_lora_repair_outputs_500.csv to nlp2_lora_repair_outputs_500.csv
dict_keys(['nlp2_lora_repair_outputs_500.csv'])

In [17]:
import pandas as pd

csv_name = list(uploaded.keys())[0]
df = pd.read_csv(csv_name)

print(df.shape)
print(df.columns)
df.head()

(500, 28)
Index(['source', 'reference', 'terms', 'base_basic', 'base_strong',
       'lora_no_term', 'lora_basic', 'lora_basic_cleaned', 'terms_dict',
       'qwen3b_basic', 'qwen3b_strong', 'qwen3b_no_term',
       'qwen3b_selected_source', 'qwen3b_selected',
       'qwen3b_selected_term_coverage', 'random_terms_dict', 'qwen3b_random',
       'selected_missing_terms', 'num_missing_selected',
       'qwen3b_selected_repaired', 'repaired_missing_terms',
       'num_missing_repaired', 'qwen3b_definition_prompt',
       'lora_cleaned_missing_terms', 'num_missing_lora_cleaned',
       'lora_basic_cleaned_repaired', 'lora_repaired_missing_terms',
       'num_missing_lora_repaired'],
      dtype='object')

,source,reference,terms,base_basic,base_strong,lora_no_term,lora_basic,lora_basic_cleaned,terms_dict,qwen3b_basic,...,num_missing_selected,qwen3b_selected_repaired,repaired_missing_terms,num_missing_repaired,qwen3b_definition_prompt,lora_cleaned_missing_terms,num_missing_lora_cleaned,lora_basic_cleaned_repaired,lora_repaired_missing_terms,num_missing_lora_repaired
0,This service describes the deployed (run-time)...,Dieser Service beschreibt den implementierten ...,"{'design': 'Entwurf', 'state': 'Zustand'}",Dieses Service beschreibt den ausgeführten (be...,Dieses Service beschreibt den ausgeführten (be...,Dieses Service beschreibt den ausgeführt- oder...,Dieses Service beschreibt den ausgeführt- oder...,Dieses Service beschreibt den ausgeführt- oder...,"{'design': 'Entwurf', 'state': 'Zustand'}",Dieser Service beschreibt den ausgeführten (la...,...,0,Dieser Service beschreibt den ausgeführten (La...,{},0,Dieser Service beschreibt den ausgeführten (La...,{},0,Dieses Service beschreibt den ausgeführt- oder...,{},0
1,Request a checkup to perform a health diagnost...,"Fordern Sie eine Kontrolle an, um eine Fehlerd...",{'check': 'Kontrolle'},"Kontrolliere bitte einen Überwachungsbesuch, u...",Kontrollieren Sie bitte einen Check auf die Du...,Gerüste ein Checkup um einen Gesundheitsdiagno...,Kontrollieren Sie Ihre Datenflussanalyse durch...,Kontrollieren Sie Ihre Datenflussanalyse durch...,{'check': 'Kontrolle'},"Eine Kontrolle anfordern, um eine gesundheitsd...",...,0,Kontrolle für eine Gesundheitsdiagnostik durch...,{},0,Eine Kontrolle für eine Gesundheitsdiagnostik ...,{},0,Kontrollieren Sie Ihre Datenflussanalyse durch...,{},0
2,The data product is still available in the pro...,Das Datenprodukt ist weiterhin in der Datenpro...,{'provider': 'Provider'},Der Datenprodukt ist noch im Angebot des Provi...,Der Datenprodukt ist immer noch im Liste der D...,Der Datenprodukt ist noch im Provider-Liste ve...,Der Datenprodukt ist noch im Provider-Liste ve...,Der Datenprodukt ist noch im Provider-Liste ve...,{'provider': 'Provider'},Der Datenprodukt ist im Datenproduktverzeichni...,...,0,Der Datenprodukt ist im Datenproduktverzeichni...,{},0,Das Datenprodukt ist im Provider-Datenproduktv...,{},0,Der Datenprodukt ist noch im Provider-Liste ve...,{},0
3,This availability match percentage is calculat...,Diese prozentuale Verfügbarkeitsübereinstimmun...,{'percentage': 'prozentual'},Diese Verfügbarkeits-Match-Prozentsatz wird au...,Diese Verfügbarkeitsübereinstimmung ist basier...,Diese Verfügbarkeits-Match-Prozentsatz wird au...,Dieses Verfügbarkeitsmatch-Prozentsatz wird au...,Dieses Verfügbarkeitsmatch-Prozentsatz wird au...,{'percentage': 'prozentual'},Diese prozentuale Verfügbarkeitsmatchquote wir...,...,0,Diese prozentuale Verfügbarkeitsmatchquote wir...,{},0,Diese prozentuale Verfügbarkeitsmatchquote wir...,{'percentage': 'prozentual'},1,Dieser Verfügbarkeitsmatch-prozentuale Wert wi...,{},0
4,Open the consumption model containing the meas...,Öffnen Sie das Verbrauchsmodell mit den Kennza...,{'consumption model': 'Verbrauchsmodell'},"Öffne das Verbrauchsmodell, das die Maßnahmen ...","Verwenden Sie den Verbrauchsmodell, der die Ma...",Öffnen Sie den Konsummodellinhalt mit den Maße...,Gerne! Hier ist die deutsche Übersetzung:\n\nÖ...,"Öffnen Sie das Verbrauchsmodell, das die Maße ...",{'consumption model': 'Verbrauchsmodell'},"Öffnen Sie das Verbrauchsmodell, das die Maßna...",...,0,"Verfügen Sie über das Verbrauchsmodell, das di...",{},0,"Öffne das Verbrauchsmodell, das die zu berücks...",{},0,"Öffnen Sie das Verbrauchsmodell, das die Maße ...",{},0

In [18]:
import os
import ast

os.makedirs("my_consistency_inputs", exist_ok=True)

def parse_terms(x):
    if isinstance(x, dict):
        return x
    if pd.isna(x):
        return {}
    if isinstance(x, str):
        try:
            value = ast.literal_eval(x)
            if isinstance(value, dict):
                return value
        except Exception:
            return {}
    return {}

if "terms_dict" not in df.columns:
    df["terms_dict"] = df["terms"].apply(parse_terms)

systems = [
    "base_basic",
    "base_strong",
    "qwen3b_basic",
    "qwen3b_strong",
    "qwen3b_selected",
    "qwen3b_selected_repaired"
]

available_systems = []

for col in systems:
    if col in df.columns:
        available_systems.append(col)
        df[col].fillna("").astype(str).to_csv(
            f"my_consistency_inputs/{col}.txt",
            index=False,
            header=False
        )

df["source"].fillna("").astype(str).to_csv(
    "my_consistency_inputs/source.txt",
    index=False,
    header=False
)

df["reference"].fillna("").astype(str).to_csv(
    "my_consistency_inputs/reference.txt",
    index=False,
    header=False
)

df[["source", "reference", "terms_dict"]].to_json(
    "my_consistency_inputs/terms.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

print("Available systems:", available_systems)

Available systems: ['base_basic', 'base_strong', 'qwen3b_basic', 'qwen3b_strong', 'qwen3b_selected', 'qwen3b_selected_repaired']

In [19]:
!sed -n '1,220p' wmt25-terminology/additional_metrics/term-consistency/script_track1.py

import pandas as pd
import os
import json
import time

import nltk
nltk.download('punkt_tab')

from termbasedmetric import TermBasedMetric

import argparse

def run_cycle(src_lang, tgt_lang, mode, filepath):
    '''
    runs evaluation for the 1st track, for a given source, target language and mode,
        collecting the statistics and the extracted data (terms, alignments, pseudoreferences)

    :param src_lang: source language
    :param tgt_lang: target language
    :param mode: evaluation mode ('proper', 'random', 'noterm')
    :param filepath: path to the directory containing the submitted files
    '''

    # collect all statistics in the format: {system: {pseudoref_choice: {macro: score, micro: score}}}
    total_stats = {}
    # read all submitted files
    file_list = [f for f in os.listdir(filepath) if f.endswith('.jsonl') and src_lang+tgt_lang in f and mode in f]

    # initializing term based metric
    TBM = TermBasedMetric(src_lang, tgt_lang, 'predefined', 'llm')

    # catching files with raised errors (deprecated)
    error_files = []
    for file in file_list:
        print(file)

        system_name = file.split('.')[0]
        # loading the submitted file
        TBM.load(system_name, mode=mode)
        # extracting keywords
        TBM.extract_keywords()
        # aligning source terms to translated sentences
        TBM.align(test=False)
        pseudoref_choices = ['first', 'frequent', 'predefined']
        var_dict = {pseudoref_choice: {'micro': 0, 'macro': 0} for pseudoref_choice in pseudoref_choices}
        flat_df = []
        for pseudoref_choice in pseudoref_choices:
            # assigning pseudoreferences for all three pseudoreference types (first, frequent, predefined)
            _, _, _, sel = TBM.assign_pseudoreferences(pseudoref_choice)
            # computing the micro and macro averaged accuracies for pseudoreference and aligned term overlaps
            micro, flat_micro = TBM.compute_metric('micro')
            macro, _ = TBM.compute_metric('macro')
            if pseudoref_choice == 'first':
                sel_first = flat_micro.copy(deep=True)
            elif pseudoref_choice == 'frequent':
                sel_freq = flat_micro.copy(deep=True)
            flat_micro.rename(columns={'pseudoref': f'pseudoref_{pseudoref_choice}'}, inplace=True)
            flat_df.append(flat_micro)
            var_dict[pseudoref_choice]['micro'] = micro
            var_dict[pseudoref_choice]['macro'] = macro
        # adding all statistics to total dict
        total_stats[system_name] = var_dict
        flat_df = pd.concat(flat_df, axis=1)
        # saving the file with pseudoreferences (and aligned term translations)
        flat_df.to_csv(f'pseudorefs/{file}_pseudoref.tsv', sep='\t')
        # saving the file with all initial data (sentences, terms, extracted translations)
        TBM.bitext_df[['terms', 'src_raw', 'mt_raw', 'src_terms', 'alg_terms', 'norm_tgt_terms']].to_csv(f'processed/{file}_processed.tsv', sep='\t')

    return total_stats, error_files


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--srclang')
    parser.add_argument('-t', '--tgtlang')
    parser.add_argument('-m', '--mode')
#    parser.add_argument('-l', '--track')
    args=parser.parse_args()
    print(args.srclang, args.tgtlang, args.mode)
    a = time.time()
    stats_dict, error_files = run_cycle(args.srclang, args.tgtlang, args.mode, f'data/submissions/track1')
    b = time.time()
    print(f'finished in {b-a} seconds')
    print(error_files)
    with open(f'stats-{args.srclang}{args.tgtlang}.{args.mode}.json', 'w') as fp:
        json.dump(stats_dict, fp)

In [20]:
!sed -n '1,220p' wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py

import pandas as pd
import json
from nltk.tokenize import word_tokenize
from openai import OpenAI
import ast
from transformers import AutoModel, AutoTokenizer
import itertools
import torch
import stanza
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score # TODO: generalize to input other metrics
from sklearn.metrics import confusion_matrix
from collections import defaultdict
import pymorphy3
import jieba


class TermBasedMetric():
    """
    Handles term-based evaluation metrics for machine translation models.

    Core methods:
    1. load: loads the submission file. Tailored to the WMT25 shared task format.
    2. extract_keywords: extracts terms from the submission file. Tailored to the explicitly predefined terminology dictionaries.
    3. align: aligns terms with the mt outputs. Current implementation uses ChatGPT + LaBSE postprocessing as an aligner.
    4. assign_pseudoreference: assigns pseudoreference terms (the terms from which the deviation would be counted) based on the selected strategy.
    5. compute_metric: computes the term-based metric based on the selected strategy (micro/macro accuracy of the aligned terms against the pseudoreference terms).

    Attributes:
        lang_src (str): Source language code (e.g., 'en').
        lang_tgt (str): Target language code (e.g., 'cs').
        stanza_src: A stanza pipeline object for processing the source language.
        stanza_tgt: A stanza pipeline object for processing the target language.
        ru_morph: A pymorphy3 MorphAnalyzer object for Russian text analysis.
        keyword_extractor (str): Specifies the keyword extraction method.
        aligner (str): Specifies the alignment algorithm.
        openai_client: OpenAI client object if aligner is 'llm'.
        aligner_model: Alignment model if aligner is 'llm' and requires models.
        aligner_tokenizer: Tokenizer for the alignment model used with 'llm'.
        failed_dummy (str): Placeholder string for failed alignments.
        pseudoref_dummy (str): Placeholder string for dummy pseudoreferences.
    """

    def __init__(self, src_lang: str, tgt_lang: str, keyword_extractor: str, aligner: str):
        # TODO: consider reallocating keyword-extractor and aligner params to extract_keywords and align methods
        # TODO: more consistent lemmatizers (stanza_src/tgt VS ru_morph for Russian VS jieba for Chinese)
        '''
        initializes the term-based metric instance.

        :param src_lang: Source language code.
        :param tgt_lang: Target language code.
        :param keyword_extractor: name of the keyword extraction principle. {'yake', 'regex', 'predefined'}, default: 'predefined'
        :param aligner: name of the automatic alignment algorithm. {'fastalign', 'awesomealign', 'llm'}, default: 'llm'
        '''
        self.lang_src, self.lang_tgt = src_lang, tgt_lang
        self.stanza_src = stanza.Pipeline(self.lang_src, processors='tokenize,lemma', lemma_pretagged=True, tokenize_pretokenized=False)
        self.stanza_tgt = stanza.Pipeline(self.lang_tgt, processors='tokenize,lemma', lemma_pretagged=True, tokenize_pretokenized=False)
        self.ru_morph = pymorphy3.MorphAnalyzer()
        self.keyword_extractor = keyword_extractor
        self.aligner = aligner
        if self.aligner == 'llm':
            with open('openai-api-key.txt', 'r', encoding='utf-8') as f:
                openai_key = f.read()
            self.openai_client = OpenAI(api_key=openai_key)
            self.aligner_model = AutoModel.from_pretrained("aneuraz/awesome-align-with-co")
            self.aligner_tokenizer = AutoTokenizer.from_pretrained("aneuraz/awesome-align-with-co")
        #self.pseudoreference_mode = pseudoreference_mode
        #self.statistical_metric = statistical_metric

        self.failed_dummy = '▔'
        self.pseudoref_dummy = '▁'


    def load(self, system: str, mode='proper', track=1, year=None,
                              file_path='data/submissions/', file_type='jsonl', return_random=False):

        """
        Loads and processes bitext data from a specified file source based on the given
        configuration, and returns the processed data as a DataFrame.
        Tailored for the WMT25 format, other formats like Moses (|||-separated) are not checked.

        Parameters:
        :param system: str
            Specifies the system name.
        :param mode: str, default 'proper'
            Specifies the terminology mode {proper, random, noterm}.
        :param track: int, default 1
            Specifies the track of the submission (1 or 2).
        :param year: Optional, default None
            Specifies the year corresponding to the data (2nd track only).
        :param file_path: str, default 'data/submissions/'
            Specifies the path to the directory containing the bitext files.
        :param file_type: str, default 'jsonl'
            Specifies the file type to be read; supported types are 'tsv', 'jsonl', or Moses format.
        :param return_random: bool, default False
            Determines whether for the random mode, the random terminology is returned
            (default is retrieving the proper terminology).

        :returns self.bitext_df: pd.DataFrame, containing bitext pairs aligned in columns `src_raw` and `mt_raw`.
        :returns self.file_config: dict, containing the configuration of the submitted file.

        """
        self.file_config = {'system': system, 'mode': mode, 'track': track, 'year': year, 'file_path': file_path, 'file_type': file_type, 'return_random': return_random}

        bitext_filepath = self._name_compiler_wmt25()

        #self.bitext_df_filename = bitext

        if file_type == 'tsv':
            bitext_df = self._open_tsv_file(bitext_filepath)
        elif file_type == 'jsonl':

            bitext_df = self._open_jsonl_file(bitext_filepath)#.head(20)

        else:
            # when it is in the moses format (src_sent ||| tgt_sent):

            with open(bitext_filepath, 'r', encoding='utf-8') as f:
                data = f.read()
            lines = data.split('\n')
            if lines[-1] == '':
                lines = lines[:-1]

            sent_pairs = []
            for line in lines: # TODO: make a list comprehension
                src, tgt = line.split(' ||| ')
                pair = [src, tgt]
                sent_pairs.append(pair)

            bitext_df = pd.DataFrame(sent_pairs, columns=['src_raw', 'mt_raw'])

        self.bitext_df = bitext_df#[['src', 'mt']]

        return self.bitext_df

    def extract_keywords(self, return_random=False):
        '''
        retrieves the list of the keywords either from the predefined file, or automatically.
        Tailored for the WMT25 format (predefined terminology), other methods like regex or YAKE are not checked.

        the keyword_extractor values are:
            - `predefined`: the manually predefined set of words in the
                            format {"src_lang term": "tgt_lang term"} format (WMT terminology shared task-2025)
            - `yake`: TODO
            - `regex`: TODO
        :return: 'src_terms' column for the self.bitext_df
        '''
        if self.keyword_extractor == 'predefined':

            terms, reference_dict = self._retrieve_predefined_terms(return_random=return_random)
            self.bitext_df['src_terms'] = terms
            if self.file_config['track'] == 2:
                self.bitext_df['terms'] = self.bitext_df['terms'].apply(lambda d: {k: v[0] for k, v in d.items()})

        elif self.keyword_extractor == 'yake':
            raise NotImplementedError
        elif self.keyword_extractor == 'regex':
            raise NotImplementedError

        return self.bitext_df

    def align(self, test=False):
        """
        Extracts the translations of the source terms from the target text, and stores them in the alignment dictionary.
        Current implementation is tailored for the WMT25 format (for languages in question, LLMs+post-filtering worked best),
        alternatives (like fast-align or awesome-align) are not implemented.

        IMPORTANT: the LLM method requires the few-shot prompt file specified by 'lang_src-lang_tgt-20.txt' in 'fewshot' folder,
                   otherwise raises IOError!

        :param test: bool  (default True), takes only last 50 rows from the bitext DataFrame for alignment.

        :return: column 'alg_terms' in self.bitext_df, dictionary containing source terms and translations extracted from the target text.
        :return: column 'over_aligned' in self.bitext_df: int (0 or 1), whether the aligned translated term includes excessive words. To be deprecated.

        """

        if test:
            df = self.bitext_df.tail(50)
            self.bitext_df = None
            self.bitext_df = df


        if self.aligner == 'llm':
            # TODO: generalize the fewshot path
            with open(f'fewshot/{self.lang_src}-{self.lang_tgt}-20.txt', 'r', encoding='utf-8') as f:
                fewshots_prompt = f.read()
            self.bitext_df['alg_terms'], self.bitext_df['over_aligned'] = zip(*self.bitext_df.apply(lambda row: self._llm_align_one_segment(row.src_raw, row.src_terms, row.mt_raw, fewshots_prompt, row.terms), axis=1))

    def assign_pseudoreferences(self, pseudoreference_mode):
        """
        Assign pseudoreferences (expected correct terms against which the real occurrences will be counted)
        to source terms based on a specified pseudoreference mode and create data structures mapping the source terms to the pseudoreferences.

        Parameters:
        :param pseudoreference_mode: str, three modes:
         - 'predefined': uses the predefined translations as pseudoreferences,
         - 'frequent': uses the most frequent translation of a term as pseudoreference,
         - 'first': uses the first translations of each term as pseudoreference,

         :return: 'norm_tgt_terms' column in self.bitext_df, list of normalized translated terms extracted for each segment.
         :return: 'pseudoref_terms' in self.bitext_df, list pseudoreferences for each segment.
         :return: df_first, df_freq, df_predef: 3 DataFrames, containing mappings of source terms to the pseudoreferences based on the specified mode.
                  (TODO: unnecessary, consider deleting)
         :return: 'pseudoreference_dict', dictionary containing ALL source terms and corresponding pseudoreferences.
        """


        self.bitext_df['norm_tgt_terms'] = self.bitext_df.apply(lambda row: self._normalize_pseudoreference_candidates(row.src_terms, row.alg_terms), axis=1)

        src_list_of_lists = self.bitext_df['src_terms'].tolist()
        tgt_list_of_lists = self.bitext_df['norm_tgt_terms'].tolist()

        # creating the pseudoreference tables for extracting the pseudoreferences
        df_first, df_freq, df_predef = self._create_pseudoreference_tables(src_list_of_lists, tgt_list_of_lists, self.bitext_df['terms'].tolist())
        if pseudoreference_mode == 'predefined':
            selected_df = df_predef
        elif pseudoreference_mode == 'frequent':
            selected_df = df_freq

In [21]:
!pip install -q pandas numpy tqdm nltk stanza pymorphy3 jieba openai transformers torch sentence-transformers scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 34.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.7/773.7 kB 59.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 51.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 97.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 418.7/418.7 kB 40.9 MB/s eta 0:00:00

In [22]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [26]:
!git clone https://github.com/wmt-conference/wmt25-terminology.git

fatal: destination path 'wmt25-terminology' already exists and is not an empty directory.

In [27]:
import pandas as pd
import ast
import os
import json

csv_name = list(uploaded.keys())[0]
df = pd.read_csv(csv_name)

print(df.shape)
print(df.columns)
df.head()

(500, 28)
Index(['source', 'reference', 'terms', 'base_basic', 'base_strong',
       'lora_no_term', 'lora_basic', 'lora_basic_cleaned', 'terms_dict',
       'qwen3b_basic', 'qwen3b_strong', 'qwen3b_no_term',
       'qwen3b_selected_source', 'qwen3b_selected',
       'qwen3b_selected_term_coverage', 'random_terms_dict', 'qwen3b_random',
       'selected_missing_terms', 'num_missing_selected',
       'qwen3b_selected_repaired', 'repaired_missing_terms',
       'num_missing_repaired', 'qwen3b_definition_prompt',
       'lora_cleaned_missing_terms', 'num_missing_lora_cleaned',
       'lora_basic_cleaned_repaired', 'lora_repaired_missing_terms',
       'num_missing_lora_repaired'],
      dtype='object')

,source,reference,terms,base_basic,base_strong,lora_no_term,lora_basic,lora_basic_cleaned,terms_dict,qwen3b_basic,...,num_missing_selected,qwen3b_selected_repaired,repaired_missing_terms,num_missing_repaired,qwen3b_definition_prompt,lora_cleaned_missing_terms,num_missing_lora_cleaned,lora_basic_cleaned_repaired,lora_repaired_missing_terms,num_missing_lora_repaired
0,This service describes the deployed (run-time)...,Dieser Service beschreibt den implementierten ...,"{'design': 'Entwurf', 'state': 'Zustand'}",Dieses Service beschreibt den ausgeführten (be...,Dieses Service beschreibt den ausgeführten (be...,Dieses Service beschreibt den ausgeführt- oder...,Dieses Service beschreibt den ausgeführt- oder...,Dieses Service beschreibt den ausgeführt- oder...,"{'design': 'Entwurf', 'state': 'Zustand'}",Dieser Service beschreibt den ausgeführten (la...,...,0,Dieser Service beschreibt den ausgeführten (La...,{},0,Dieser Service beschreibt den ausgeführten (La...,{},0,Dieses Service beschreibt den ausgeführt- oder...,{},0
1,Request a checkup to perform a health diagnost...,"Fordern Sie eine Kontrolle an, um eine Fehlerd...",{'check': 'Kontrolle'},"Kontrolliere bitte einen Überwachungsbesuch, u...",Kontrollieren Sie bitte einen Check auf die Du...,Gerüste ein Checkup um einen Gesundheitsdiagno...,Kontrollieren Sie Ihre Datenflussanalyse durch...,Kontrollieren Sie Ihre Datenflussanalyse durch...,{'check': 'Kontrolle'},"Eine Kontrolle anfordern, um eine gesundheitsd...",...,0,Kontrolle für eine Gesundheitsdiagnostik durch...,{},0,Eine Kontrolle für eine Gesundheitsdiagnostik ...,{},0,Kontrollieren Sie Ihre Datenflussanalyse durch...,{},0
2,The data product is still available in the pro...,Das Datenprodukt ist weiterhin in der Datenpro...,{'provider': 'Provider'},Der Datenprodukt ist noch im Angebot des Provi...,Der Datenprodukt ist immer noch im Liste der D...,Der Datenprodukt ist noch im Provider-Liste ve...,Der Datenprodukt ist noch im Provider-Liste ve...,Der Datenprodukt ist noch im Provider-Liste ve...,{'provider': 'Provider'},Der Datenprodukt ist im Datenproduktverzeichni...,...,0,Der Datenprodukt ist im Datenproduktverzeichni...,{},0,Das Datenprodukt ist im Provider-Datenproduktv...,{},0,Der Datenprodukt ist noch im Provider-Liste ve...,{},0
3,This availability match percentage is calculat...,Diese prozentuale Verfügbarkeitsübereinstimmun...,{'percentage': 'prozentual'},Diese Verfügbarkeits-Match-Prozentsatz wird au...,Diese Verfügbarkeitsübereinstimmung ist basier...,Diese Verfügbarkeits-Match-Prozentsatz wird au...,Dieses Verfügbarkeitsmatch-Prozentsatz wird au...,Dieses Verfügbarkeitsmatch-Prozentsatz wird au...,{'percentage': 'prozentual'},Diese prozentuale Verfügbarkeitsmatchquote wir...,...,0,Diese prozentuale Verfügbarkeitsmatchquote wir...,{},0,Diese prozentuale Verfügbarkeitsmatchquote wir...,{'percentage': 'prozentual'},1,Dieser Verfügbarkeitsmatch-prozentuale Wert wi...,{},0
4,Open the consumption model containing the meas...,Öffnen Sie das Verbrauchsmodell mit den Kennza...,{'consumption model': 'Verbrauchsmodell'},"Öffne das Verbrauchsmodell, das die Maßnahmen ...","Verwenden Sie den Verbrauchsmodell, der die Ma...",Öffnen Sie den Konsummodellinhalt mit den Maße...,Gerne! Hier ist die deutsche Übersetzung:\n\nÖ...,"Öffnen Sie das Verbrauchsmodell, das die Maße ...",{'consumption model': 'Verbrauchsmodell'},"Öffnen Sie das Verbrauchsmodell, das die Maßna...",...,0,"Verfügen Sie über das Verbrauchsmodell, das di...",{},0,"Öffne das Verbrauchsmodell, das die zu berücks...",{},0,"Öffnen Sie das Verbrauchsmodell, das die Maße ...",{},0

In [28]:
possible_systems = [
    "base_basic",
    "base_strong",
    "qwen3b_basic",
    "qwen3b_strong",
    "qwen3b_selected",
    "qwen3b_selected_repaired"
]

for col in possible_systems:
    print(col, col in df.columns)

base_basic True
base_strong True
qwen3b_basic True
qwen3b_strong True
qwen3b_selected True
qwen3b_selected_repaired True

In [30]:
%cd /content/wmt25-terminology/additional_metrics/term-consistency

/content/wmt25-terminology/additional_metrics/term-consistency

In [31]:
from script_track1 import run_cycle
print("run_cycle imported")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:44: SyntaxWarning: invalid escape sequence '\.'
  re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:46: SyntaxWarning: invalid escape sequence '\s'
  re_skip_default = re.compile("(\r\n|\s)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/finalseg/__init__.py:78: SyntaxWarning: invalid escape sequence '\.'
  re_skip = re.compile("([a-zA-Z0-9]+(?:\.\d+)?%?)")

run_cycle imported

In [32]:
import os

os.makedirs("processed", exist_ok=True)
os.makedirs("pseudorefs", exist_ok=True)
os.makedirs("stats", exist_ok=True)

In [33]:
stats_dict, error_files = run_cycle(
    src_lang="en",
    tgt_lang="de",
    mode="proper",
    filepath="data/submissions/track1"
)

print(stats_dict)
print(error_files)

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
WARNING:stanza:Language en package default expects mwt, which has been added

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.12.0/models/tokenize/combined.pt:   0%|   …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.12.0/models/mwt/combined.pt:   0%|        …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.12.0/models/lemma/combined_nocharlm.pt:   …

INFO:stanza:Loading these models for language: en (English):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

INFO:stanza:Using device: cuda
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: lemma
INFO:stanza:Done loading processors!
INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
WARNING:stanza:Language de package default expects mwt, which has been added

Downloading https://huggingface.co/stanfordnlp/stanza-de/resolve/v1.12.0/models/tokenize/combined.pt:   0%|   …

Downloading https://huggingface.co/stanfordnlp/stanza-de/resolve/v1.12.0/models/mwt/combined.pt:   0%|        …

Downloading https://huggingface.co/stanfordnlp/stanza-de/resolve/v1.12.0/models/lemma/combined_nocharlm.pt:   …

INFO:stanza:Loading these models for language: de (German):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

INFO:stanza:Using device: cuda
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: lemma
INFO:stanza:Done loading processors!
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

BertModel LOAD REPORT from: aneuraz/awesome-align-with-co
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
psi_cls.decoder.bias                       | UNEXPECTED |
guide_layer.linear2.bias                   | UNEXPECTED |
psi_cls.bias                               | UNEXPECTED |
psi_cls.decoder.weight                     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
guide_layer.linear.weight                  | UNEXPECTED |
guide_layer.linear2.weight                 | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
guide_layer.linear.bias                    | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
psi_cls.transform.weight                   | UNEXPECTED |
psi_cls.transform.bias                     | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/40.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

{}
[]

In [34]:
print("Notebook is responsive")

Notebook is responsive

In [35]:
"run_cycle" in globals()

True

In [36]:
!pwd

/content/wmt25-terminology/additional_metrics/term-consistency

In [37]:
!ls -lh
!ls -lh processed 2>/dev/null
!ls -lh pseudorefs 2>/dev/null
!ls -lh stats 2>/dev/null

total 140K
drwxr-xr-x 3 root root 4.0K May 20 21:28 data
-rw-r--r-- 1 root root  17K May 20 21:28 docpreprocessor.py
drwxr-xr-x 2 root root 4.0K May 20 21:28 fewshot
-rw-r--r-- 1 root root   21 May 20 21:28 openai-api-key.txt
drwxr-xr-x 2 root root 4.0K May 20 21:28 processed
drwxr-xr-x 2 root root 4.0K May 20 21:28 pseudorefs
drwxr-xr-x 2 root root 4.0K May 20 22:25 __pycache__
-rw-r--r-- 1 root root 2.4K May 20 21:28 README.md
-rw-r--r-- 1 root root  18K May 20 21:28 requirements.txt
-rw-r--r-- 1 root root 3.7K May 20 21:28 script_track1.py
-rw-r--r-- 1 root root 3.5K May 20 21:28 script_track2.py
drwxr-xr-x 2 root root 4.0K May 20 21:28 stats
-rw-r--r-- 1 root root  38K May 20 21:28 termbasedmetric.py
-rw-r--r-- 1 root root  19K May 20 21:28 track2-sent-alignment.ipynb
total 21M
-rw-r--r-- 1 root root 21M May 20 21:28 processed.zip
-rw-r--r-- 1 root root  51 May 20 21:28 README.md
total 3.4M
-rw-r--r-- 1 root root 3.4M May 20 21:28 pseudorefs.zip
-rw-r--r-- 1 root root   52 May 20 21:28 README.md
total 80K
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-ende.noterm.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-ende.proper.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-ende.random.json
-rw-r--r-- 1 root root 4.5K May 20 21:28 stats-enes.noterm.json
-rw-r--r-- 1 root root 4.5K May 20 21:28 stats-enes.proper.json
-rw-r--r-- 1 root root 4.5K May 20 21:28 stats-enes.random.json
-rw-r--r-- 1 root root 3.9K May 20 21:28 stats-enru.noterm.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-enru.proper.json
-rw-r--r-- 1 root root 3.9K May 20 21:28 stats-enru.random.json
-rw-r--r-- 1 root root 4.3K May 20 21:28 stats-enzh.noterm.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-enzh.proper.json
-rw-r--r-- 1 root root 4.0K May 20 21:28 stats-enzh.random.json
-rw-r--r-- 1 root root 4.0K May 20 21:28 stats-zhen.noterm.json
-rw-r--r-- 1 root root 4.2K May 20 21:28 stats-zhen.proper.json
-rw-r--r-- 1 root root 3.6K May 20 21:28 stats-zhen.random.json

In [38]:
!ls -lh data/submissions/track1

total 4.0K
-rw-r--r-- 1 root root 61 May 20 21:28 README.md

In [39]:
!python script_track1.py -s en -t de -m proper

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
en de proper
2026-05-20 22:41:08 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json: 450kB [00:00, 53.5MB/s]
2026-05-20 22:41:08 INFO: Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
2026-05-20 22:41:08 WARNING: Language en package default expects mwt, which has been added
2026-05-20 22:41:08 INFO: Loading these models for language: en (English):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

2026-05-20 22:41:08 INFO: Using device: cuda
2026-05-20 22:41:08 INFO: Loading: tokenize
2026-05-20 22:41:08 INFO: Loading: mwt
2026-05-20 22:41:08 INFO: Loading: lemma
2026-05-20 22:41:09 INFO: Done loading processors!
2026-05-20 22:41:09 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json: 450kB [00:00, 49.2MB/s]
2026-05-20 22:41:09 INFO: Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
2026-05-20 22:41:09 WARNING: Language de package default expects mwt, which has been added
2026-05-20 22:41:09 INFO: Loading these models for language: de (German):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

2026-05-20 22:41:09 INFO: Using device: cuda
2026-05-20 22:41:09 INFO: Loading: tokenize
2026-05-20 22:41:09 INFO: Loading: mwt
2026-05-20 22:41:09 INFO: Loading: lemma
2026-05-20 22:41:18 INFO: Done loading processors!
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 197/197 [00:00<00:00, 1336.42it/s, Materializing param=encoder.layer.11.output.dense.weight]
BertModel LOAD REPORT from: aneuraz/awesome-align-with-co
Key                                        | Status     |
-------------------------------------------+------------+-
psi_cls.decoder.bias                       | UNEXPECTED |
psi_cls.decoder.weight                     | UNEXPECTED |
psi_cls.bias                               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
psi_cls.transform.bias                     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
guide_layer.linear.bias                    | UNEXPECTED |
guide_layer.linear2.bias                   | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
psi_cls.transform.weight                   | UNEXPECTED |
guide_layer.linear2.weight                 | UNEXPECTED |
guide_layer.linear.weight                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
finished in 13.080330848693848 seconds
[]

In [40]:
!ls -lh
!ls -lh processed 2>/dev/null
!ls -lh pseudorefs 2>/dev/null
!ls -lh stats 2>/dev/null
!ls -lh *.json 2>/dev/null

total 144K
drwxr-xr-x 3 root root 4.0K May 20 21:28 data
-rw-r--r-- 1 root root  17K May 20 21:28 docpreprocessor.py
drwxr-xr-x 2 root root 4.0K May 20 21:28 fewshot
-rw-r--r-- 1 root root   21 May 20 21:28 openai-api-key.txt
drwxr-xr-x 2 root root 4.0K May 20 21:28 processed
drwxr-xr-x 2 root root 4.0K May 20 21:28 pseudorefs
drwxr-xr-x 2 root root 4.0K May 20 22:25 __pycache__
-rw-r--r-- 1 root root 2.4K May 20 21:28 README.md
-rw-r--r-- 1 root root  18K May 20 21:28 requirements.txt
-rw-r--r-- 1 root root 3.7K May 20 21:28 script_track1.py
-rw-r--r-- 1 root root 3.5K May 20 21:28 script_track2.py
drwxr-xr-x 2 root root 4.0K May 20 21:28 stats
-rw-r--r-- 1 root root    2 May 20 22:41 stats-ende.proper.json
-rw-r--r-- 1 root root  38K May 20 21:28 termbasedmetric.py
-rw-r--r-- 1 root root  19K May 20 21:28 track2-sent-alignment.ipynb
total 21M
-rw-r--r-- 1 root root 21M May 20 21:28 processed.zip
-rw-r--r-- 1 root root  51 May 20 21:28 README.md
total 3.4M
-rw-r--r-- 1 root root 3.4M May 20 21:28 pseudorefs.zip
-rw-r--r-- 1 root root   52 May 20 21:28 README.md
total 80K
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-ende.noterm.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-ende.proper.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-ende.random.json
-rw-r--r-- 1 root root 4.5K May 20 21:28 stats-enes.noterm.json
-rw-r--r-- 1 root root 4.5K May 20 21:28 stats-enes.proper.json
-rw-r--r-- 1 root root 4.5K May 20 21:28 stats-enes.random.json
-rw-r--r-- 1 root root 3.9K May 20 21:28 stats-enru.noterm.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-enru.proper.json
-rw-r--r-- 1 root root 3.9K May 20 21:28 stats-enru.random.json
-rw-r--r-- 1 root root 4.3K May 20 21:28 stats-enzh.noterm.json
-rw-r--r-- 1 root root 3.8K May 20 21:28 stats-enzh.proper.json
-rw-r--r-- 1 root root 4.0K May 20 21:28 stats-enzh.random.json
-rw-r--r-- 1 root root 4.0K May 20 21:28 stats-zhen.noterm.json
-rw-r--r-- 1 root root 4.2K May 20 21:28 stats-zhen.proper.json
-rw-r--r-- 1 root root 3.6K May 20 21:28 stats-zhen.random.json
-rw-r--r-- 1 root root 2 May 20 22:41 stats-ende.proper.json

In [41]:
from google.colab import files

!zip nlp2_official_consistency_attempt.zip \
stats-ende.proper.json \
processed/* \
pseudorefs/*

files.download("nlp2_official_consistency_attempt.zip")

  adding: stats-ende.proper.json (stored 0%)
  adding: processed/processed.zip (stored 0%)
  adding: processed/README.md (deflated 6%)
  adding: pseudorefs/pseudorefs.zip (stored 0%)
  adding: pseudorefs/README.md (deflated 6%)

In [42]:
!cat stats-ende.proper.json

{}

In [43]:
!find data/submissions/track1 -maxdepth 3 -type f -name "*.jsonl" -print

In [44]:
!ls -lh data/submissions/track1

total 4.0K
-rw-r--r-- 1 root root 61 May 20 21:28 README.md

In [45]:
%cd /content/wmt25-terminology/additional_metrics/term-consistency

/content/wmt25-terminology/additional_metrics/term-consistency

In [46]:
import os
import json
import ast
import pandas as pd

os.makedirs("data/submissions/track1", exist_ok=True)

def parse_terms(x):
    if isinstance(x, dict):
        return x
    if pd.isna(x):
        return {}
    if isinstance(x, str):
        try:
            value = ast.literal_eval(x)
            if isinstance(value, dict):
                return value
        except Exception:
            return {}
    return {}

if "terms_dict" not in df.columns:
    df["terms_dict"] = df["terms"].apply(parse_terms)

def write_official_style_jsonl(system_col, filename):
    path = f"data/submissions/track1/{filename}"

    with open(path, "w", encoding="utf-8") as f:
        for _, row in df.iterrows():
            record = {
                "en": str(row["source"]),
                "de": str(row[system_col]),
                "terms": row["terms_dict"]
            }
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    print("Wrote:", path)

systems_to_write = [
    ("qwen3b_strong", "qwen3b_strong.ende.proper.jsonl"),
    ("qwen3b_selected", "qwen3b_selected.ende.proper.jsonl"),
    ("qwen3b_selected_repaired", "qwen3b_selected_repaired.ende.proper.jsonl"),
]

for col, filename in systems_to_write:
    if col in df.columns:
        write_official_style_jsonl(col, filename)
    else:
        print("Missing column:", col)

Wrote: data/submissions/track1/qwen3b_strong.ende.proper.jsonl
Wrote: data/submissions/track1/qwen3b_selected.ende.proper.jsonl
Wrote: data/submissions/track1/qwen3b_selected_repaired.ende.proper.jsonl

In [47]:
!ls -lh data/submissions/track1
!head -1 data/submissions/track1/qwen3b_selected_repaired.ende.proper.jsonl

total 304K
-rw-r--r-- 1 root root 98K May 20 22:51 qwen3b_selected.ende.proper.jsonl
-rw-r--r-- 1 root root 98K May 20 22:51 qwen3b_selected_repaired.ende.proper.jsonl
-rw-r--r-- 1 root root 97K May 20 22:51 qwen3b_strong.ende.proper.jsonl
-rw-r--r-- 1 root root  61 May 20 21:28 README.md
{"en": "This service describes the deployed (run-time) state of SAP HANA database artifacts, for example: tables, views, or procedures, which have been created or adjusted by the SAP Integrated Development Environment (WebIDE) editors as a family of consistent design-time artifacts for all key SAP HANA platform database features.", "de": "Dieser Service beschreibt den ausgeführten (Laufzeit-) Zustand von SAP HANA-Datenbankobjekten, zum Beispiel Tabellen, Ansichten oder Prozeduren, die durch die SAP Integrated Development Environment (WebIDE)-Editor als eine Familie von einheitlichen Entwurfsobjekten für alle Schlüsselfunktionen der SAP HANA Plattform erstellt oder angepasst wurden.", "terms": "{'design': 'Entwurf', 'state': 'Zustand'}"}

In [48]:
!python script_track1.py -s en -t de -m proper

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
en de proper
2026-05-20 22:53:07 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json: 450kB [00:00, 54.2MB/s]
2026-05-20 22:53:07 INFO: Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
2026-05-20 22:53:07 WARNING: Language en package default expects mwt, which has been added
2026-05-20 22:53:07 INFO: Loading these models for language: en (English):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

2026-05-20 22:53:07 INFO: Using device: cuda
2026-05-20 22:53:07 INFO: Loading: tokenize
2026-05-20 22:53:07 INFO: Loading: mwt
2026-05-20 22:53:07 INFO: Loading: lemma
2026-05-20 22:53:08 INFO: Done loading processors!
2026-05-20 22:53:08 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json: 450kB [00:00, 47.5MB/s]
2026-05-20 22:53:08 INFO: Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
2026-05-20 22:53:08 WARNING: Language de package default expects mwt, which has been added
2026-05-20 22:53:08 INFO: Loading these models for language: de (German):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

2026-05-20 22:53:08 INFO: Using device: cuda
2026-05-20 22:53:08 INFO: Loading: tokenize
2026-05-20 22:53:08 INFO: Loading: mwt
2026-05-20 22:53:08 INFO: Loading: lemma
2026-05-20 22:53:17 INFO: Done loading processors!
Loading weights:  41% 80/197 [00:00<00:00, 5661.48it/s, Materializing param=encoder.layer.4.intermediate.dense.bias]Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 197/197 [00:00<00:00, 1254.26it/s, Materializing param=encoder.layer.11.output.dense.weight]
BertModel LOAD REPORT from: aneuraz/awesome-align-with-co
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
guide_layer.linear.bias                    | UNEXPECTED |
guide_layer.linear.weight                  | UNEXPECTED |
psi_cls.decoder.bias                       | UNEXPECTED |
psi_cls.transform.bias                     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
guide_layer.linear2.bias                   | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
psi_cls.bias                               | UNEXPECTED |
psi_cls.transform.weight                   | UNEXPECTED |
guide_layer.linear2.weight                 | UNEXPECTED |
psi_cls.decoder.weight                     | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
pooler.dense.bias                          | MISSING    |
pooler.dense.weight                        | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
qwen3b_strong.ende.proper.jsonl
Traceback (most recent call last):
  File "/content/wmt25-terminology/additional_metrics/term-consistency/script_track1.py", line 81, in <module>
    stats_dict, error_files = run_cycle(args.srclang, args.tgtlang, args.mode, f'data/submissions/track1')
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/wmt25-terminology/additional_metrics/term-consistency/script_track1.py", line 41, in run_cycle
    TBM.extract_keywords()
  File "/content/wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py", line 151, in extract_keywords
    terms, reference_dict = self._retrieve_predefined_terms(return_random=return_random)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py", line 348, in _retrieve_predefined_terms
    filtered_term_column = [list(segment.keys()) for segment in term_column]
                                 ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

In [49]:
!cat stats-ende.proper.json

{}

In [50]:
%cd /content/wmt25-terminology/additional_metrics/term-consistency

/content/wmt25-terminology/additional_metrics/term-consistency

In [51]:
import ast
import json
import os
import pandas as pd

def force_parse_terms(x):
    if isinstance(x, dict):
        return x

    if pd.isna(x):
        return {}

    if isinstance(x, str):
        # Try Python dict string first: "{'a': 'b'}"
        try:
            value = ast.literal_eval(x)
            if isinstance(value, dict):
                return value
        except Exception:
            pass

        # Try JSON dict string: '{"a": "b"}'
        try:
            value = json.loads(x)
            if isinstance(value, dict):
                return value
        except Exception:
            pass

    return {}

# Always force-parse, even if terms_dict already exists
if "terms_dict" in df.columns:
    df["terms_dict_fixed"] = df["terms_dict"].apply(force_parse_terms)
else:
    df["terms_dict_fixed"] = df["terms"].apply(force_parse_terms)

print(type(df.loc[0, "terms_dict_fixed"]))
print(df.loc[0, "terms_dict_fixed"])

<class 'dict'>
{'design': 'Entwurf', 'state': 'Zustand'}

In [52]:
!rm -f data/submissions/track1/*.jsonl
!ls -lh data/submissions/track1

total 4.0K
-rw-r--r-- 1 root root 61 May 20 21:28 README.md

In [53]:
os.makedirs("data/submissions/track1", exist_ok=True)

def write_official_style_jsonl(system_col, filename):
    path = f"data/submissions/track1/{filename}"

    with open(path, "w", encoding="utf-8") as f:
        for _, row in df.iterrows():
            terms_obj = row["terms_dict_fixed"]

            record = {
                "src": str(row["source"]),
                "source": str(row["source"]),
                "src_raw": str(row["source"]),
                "mt": str(row[system_col]),
                "target": str(row[system_col]),
                "mt_raw": str(row[system_col]),
                "reference": str(row["reference"]),
                "terms": terms_obj
            }

            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    print("Wrote:", path)

systems_to_write = [
    ("qwen3b_strong", "qwen3b_strong.ende.proper.jsonl"),
    ("qwen3b_selected", "qwen3b_selected.ende.proper.jsonl"),
    ("qwen3b_selected_repaired", "qwen3b_selected_repaired.ende.proper.jsonl"),
]

for col, filename in systems_to_write:
    if col in df.columns:
        write_official_style_jsonl(col, filename)
    else:
        print("Missing column:", col)

Wrote: data/submissions/track1/qwen3b_strong.ende.proper.jsonl
Wrote: data/submissions/track1/qwen3b_selected.ende.proper.jsonl
Wrote: data/submissions/track1/qwen3b_selected_repaired.ende.proper.jsonl

In [54]:
!head -1 data/submissions/track1/qwen3b_selected_repaired.ende.proper.jsonl

{"src": "This service describes the deployed (run-time) state of SAP HANA database artifacts, for example: tables, views, or procedures, which have been created or adjusted by the SAP Integrated Development Environment (WebIDE) editors as a family of consistent design-time artifacts for all key SAP HANA platform database features.", "source": "This service describes the deployed (run-time) state of SAP HANA database artifacts, for example: tables, views, or procedures, which have been created or adjusted by the SAP Integrated Development Environment (WebIDE) editors as a family of consistent design-time artifacts for all key SAP HANA platform database features.", "src_raw": "This service describes the deployed (run-time) state of SAP HANA database artifacts, for example: tables, views, or procedures, which have been created or adjusted by the SAP Integrated Development Environment (WebIDE) editors as a family of consistent design-time artifacts for all key SAP HANA platform database features.", "mt": "Dieser Service beschreibt den ausgeführten (Laufzeit-) Zustand von SAP HANA-Datenbankobjekten, zum Beispiel Tabellen, Ansichten oder Prozeduren, die durch die SAP Integrated Development Environment (WebIDE)-Editor als eine Familie von einheitlichen Entwurfsobjekten für alle Schlüsselfunktionen der SAP HANA Plattform erstellt oder angepasst wurden.", "target": "Dieser Service beschreibt den ausgeführten (Laufzeit-) Zustand von SAP HANA-Datenbankobjekten, zum Beispiel Tabellen, Ansichten oder Prozeduren, die durch die SAP Integrated Development Environment (WebIDE)-Editor als eine Familie von einheitlichen Entwurfsobjekten für alle Schlüsselfunktionen der SAP HANA Plattform erstellt oder angepasst wurden.", "mt_raw": "Dieser Service beschreibt den ausgeführten (Laufzeit-) Zustand von SAP HANA-Datenbankobjekten, zum Beispiel Tabellen, Ansichten oder Prozeduren, die durch die SAP Integrated Development Environment (WebIDE)-Editor als eine Familie von einheitlichen Entwurfsobjekten für alle Schlüsselfunktionen der SAP HANA Plattform erstellt oder angepasst wurden.", "reference": "Dieser Service beschreibt den implementierten Zustand (Laufzeitzustand) von SAP-HANA-Datenbankartefakten, z. B. Tabellen, Views oder Prozeduren, die von den SAP-Integrated-Development-Environment-Editoren (WebIDE-Editoren) als eine Familie konsistenter Entwurfszeit-Artefakte für alle wichtigen SAP-HANA-Plattform-Datenbankfunktionen erstellt oder angepasst wurden.", "terms": {"design": "Entwurf", "state": "Zustand"}}

In [55]:
!python script_track1.py -s en -t de -m proper

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
en de proper
2026-05-20 23:02:15 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json: 450kB [00:00, 46.3MB/s]
2026-05-20 23:02:15 INFO: Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
2026-05-20 23:02:15 WARNING: Language en package default expects mwt, which has been added
2026-05-20 23:02:15 INFO: Loading these models for language: en (English):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

2026-05-20 23:02:15 INFO: Using device: cuda
2026-05-20 23:02:15 INFO: Loading: tokenize
2026-05-20 23:02:15 INFO: Loading: mwt
2026-05-20 23:02:15 INFO: Loading: lemma
2026-05-20 23:02:16 INFO: Done loading processors!
2026-05-20 23:02:16 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.12.0.json: 450kB [00:00, 43.3MB/s]
2026-05-20 23:02:16 INFO: Downloaded file to /root/.cache/stanza/1.12.0/resources/resources.json
2026-05-20 23:02:16 WARNING: Language de package default expects mwt, which has been added
2026-05-20 23:02:16 INFO: Loading these models for language: de (German):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

2026-05-20 23:02:16 INFO: Using device: cuda
2026-05-20 23:02:16 INFO: Loading: tokenize
2026-05-20 23:02:16 INFO: Loading: mwt
2026-05-20 23:02:16 INFO: Loading: lemma
2026-05-20 23:02:25 INFO: Done loading processors!
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 197/197 [00:00<00:00, 1079.22it/s, Materializing param=encoder.layer.11.output.dense.weight]
BertModel LOAD REPORT from: aneuraz/awesome-align-with-co
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
psi_cls.bias                               | UNEXPECTED |
psi_cls.decoder.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
guide_layer.linear2.bias                   | UNEXPECTED |
psi_cls.transform.weight                   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
guide_layer.linear.bias                    | UNEXPECTED |
psi_cls.decoder.weight                     | UNEXPECTED |
guide_layer.linear.weight                  | UNEXPECTED |
psi_cls.transform.bias                     | UNEXPECTED |
guide_layer.linear2.weight                 | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.bias                          | MISSING    |
pooler.dense.weight                        | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
qwen3b_strong.ende.proper.jsonl
Traceback (most recent call last):
  File "/content/wmt25-terminology/additional_metrics/term-consistency/script_track1.py", line 81, in <module>
    stats_dict, error_files = run_cycle(args.srclang, args.tgtlang, args.mode, f'data/submissions/track1')
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/wmt25-terminology/additional_metrics/term-consistency/script_track1.py", line 43, in run_cycle
    TBM.align(test=False)
  File "/content/wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py", line 189, in align
    self.bitext_df['alg_terms'], self.bitext_df['over_aligned'] = zip(*self.bitext_df.apply(lambda row: self._llm_align_one_segment(row.src_raw, row.src_terms, row.mt_raw, fewshots_prompt, row.terms), axis=1))
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py", line 189, in <lambda>
    self.bitext_df['alg_terms'], self.bitext_df['over_aligned'] = zip(*self.bitext_df.apply(lambda row: self._llm_align_one_segment(row.src_raw, row.src_terms, row.mt_raw, fewshots_prompt, row.terms), axis=1))
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py", line 371, in _llm_align_one_segment
    alg_term = self._llm_prompt_alignment(src_sent, src_term, tgt_sent, fewshots)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/wmt25-terminology/additional_metrics/term-consistency/termbasedmetric.py", line 401, in _llm_prompt_alignment
    completion = self.openai_client.chat.completions.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_utils/_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/resources/chat/completions/completions.py", line 1211, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1314, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1087, in request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: {paste y*********ere}. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

In [56]:
!cat stats-ende.proper.json

{}

In [57]:
from google.colab import files


with open("official_consistency_attempt_notes.txt", "w") as f:
    f.write("""Official WMT term-consistency script attempt.

The script was able to load the English/German Stanza pipelines and the alignment model,
and it found the generated submission file. However, it failed during the LLM-based
term alignment step because the implementation requires a valid OpenAI API key.

Therefore, we did not use the official consistency metric in the report. Instead, we report
a lightweight repeated-term consistency diagnostic computed directly from required target-term matches.
""")

!zip nlp2_official_consistency_attempt_evidence.zip \
official_consistency_attempt_notes.txt \
stats-ende.proper.json \
data/submissions/track1/*.jsonl

files.download("nlp2_official_consistency_attempt_evidence.zip")

  adding: official_consistency_attempt_notes.txt (deflated 41%)
  adding: stats-ende.proper.json (stored 0%)
  adding: data/submissions/track1/qwen3b_selected.ende.proper.jsonl (deflated 83%)
  adding: data/submissions/track1/qwen3b_selected_repaired.ende.proper.jsonl (deflated 83%)
  adding: data/submissions/track1/qwen3b_strong.ende.proper.jsonl (deflated 82%)